set -g default-terminal tmux-256color
set -g prefix C-a
set -g mouse on
set -g base-index 1

bind C-a send-prefix
unbind C-b

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind R source-file ~/.tmux.conf \; display-message "source-file done"

set -g menu-style fg=color208
set -g menu-border-style fg=color208

set -g status-interval 1
set -g status-justify absolute-centre
set -g status-left " [#S] #(vmstat -S M | tail -1 | awk '{print \"CPU Idle: \" $15 \"% | Mem Avail: \" $4+$6 \"MB\"}') "
set -g status-left-length 40
set -g status-left-style bg=color038
set -g status-right ' Tasks: #(pgrep -c -U $USER -r R)/#(pgrep -c -U $USER -r S)/#(pgrep -c -U $USER -r D) | %Y-%m-%d %H:%M:%S '
set -g status-right-length 40
set -g status-right-style bg=white
set -g status-style fg=black,bg=color176

set -g copy-mode-selection-style fg=white,bg=color055
set -g mode-style fg=black,bg=color208

set -g pane-active-border-style fg=yellow
set -g pane-border-style fg=red

set -g window-status-current-style reverse
